// Generated by hand from the Supabase migration. Refresh with `supabase gen types` later.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  courses: {
    Tables: {
      households: {
        Row: {
          id: string;
          name: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_by: string;
          created_at?: string;
        };
        Update: Partial<Database["courses"]["Tables"]["households"]["Insert"]>;
        Relationships: [];
      };
      household_members: {
        Row: {
          household_id: string;
          user_id: string;
          display_name: string;
          role: "owner" | "member";
          joined_at: string;
        };
        Insert: {
          household_id: string;
          user_id: string;
          display_name: string;
          role?: "owner" | "member";
          joined_at?: string;
        };
        Update: Partial<
          Database["courses"]["Tables"]["household_members"]["Insert"]
        >;
        Relationships: [];
      };
      meal_plans: {
        Row: {
          id: string;
          household_id: string;
          date: string;
          slot: "lunch" | "dinner";
          title: string;
          notes: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          date: string;
          slot: "lunch" | "dinner";
          title: string;
          notes?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["courses"]["Tables"]["meal_plans"]["Insert"]>;
        Relationships: [];
      };
      shopping_items: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          quantity: string | null;
          category: string | null;
          meal_plan_id: string | null;
          checked_at: string | null;
          checked_by: string | null;
          cleared_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          quantity?: string | null;
          category?: string | null;
          meal_plan_id?: string | null;
          checked_at?: string | null;
          checked_by?: string | null;
          cleared_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["courses"]["Tables"]["shopping_items"]["Insert"]
        >;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_household: {
        Args: { p_name: string; p_display_name: string };
        Returns: string;
      };
      is_household_member: {
        Args: { hh_id: string };
        Returns: boolean;
      };
      is_household_owner: {
        Args: { hh_id: string };
        Returns: boolean;
      };
      create_invite: {
        Args: { p_household_id: string; p_default_display_name: string | null };
        Returns: string;
      };
      peek_invite: {
        Args: { p_token: string };
        Returns: {
          household_id: string;
          household_name: string;
          default_display_name: string | null;
          expired: boolean;
          used: boolean;
        }[];
      };
      redeem_invite: {
        Args: { p_token: string; p_display_name: string };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type HouseholdRow = Database["courses"]["Tables"]["households"]["Row"];
export type HouseholdMemberRow =
  Database["courses"]["Tables"]["household_members"]["Row"];
export type MealPlanRow = Database["courses"]["Tables"]["meal_plans"]["Row"];
export type ShoppingItemRow =
  Database["courses"]["Tables"]["shopping_items"]["Row"];
